#!/bin/bash

IPADDRESS=$(/sbin/ifconfig eth0 | sed -n 's/.*inet addr:\([^ ]*\).*/\1/p')
if [[ -z $IPADDRESS ]]
then
 exit
fi


if [[ "${IPADDRESS}" != $(cat ~/.current_ip) ]]
then
 echo "workstation IP address is ${IPADDRESS}" | mail -s "Workstation IP address change" <email>
 echo ${IPADDRESS} >|~/.current_ip
fi
