#!/bin/bash

files="zshrc vim vimrc gitconfig bashrc"
dir=$HOME/dotfiles
backup=.dotfiles_old
prog="zsh wget git"

mkdir -p ../$backup

sudo apt-get install -y $prog

# we need nice editor
wget https://atom.io/download/deb
sudo dpkg -i deb

# and some addons to it
sudo apm install linter linter-less linter-pylint linter-jscs linter-phpcs block-travel linter-jshint linter-phpmd linter-csslint linter-pep8 linter-shellcheck linter-htmlhint linter-php linter-xmllint
# and the uber config
ln -s $dir/atomConfig.cson $HOME/.atom/config.cson 

sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

###########################
# Backup old fils.
# Removes them then symlink 
###########################
for file in $files;
do
	rsync -arv ../.$file ../$backup/
	rm -Rf ../.$file
	rm ../.$file
	ln -s $dir/$file $HOME/.$file
done
source zshrc
